
name: M3-NonFunctional_PSD_Test

on:
  workflow_run:
    workflows: [M2_Functional_PSD_Test]
    types: [completed]
    
  workflow_dispatch:
    inputs:
       logLevel:
          description: 'Log level'     
          required: true
          default: 'warning'
       tags:
          description: 'Test scenario tags'

jobs:
  Performance_Test:
    runs-on: PSD
    if: ${{ github.event.workflow_run.conclusion == 'success' }} && runner.name == 'psd'
    steps:
    - run: |
        echo "execute Performance_Test in M3-NonFunctional_PSD_Test"

  Sustained_Performance_test:
    runs-on: PSD
    if: ${{ github.event.workflow_run.conclusion == 'success' }} && runner.name == 'psd'
    steps:
    - run: |
        echo "execute Sustained_Performance_test in M3-NonFunctional_PSD_Test"

  on-failure:
    runs-on: PSD
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'The triggering workflow failed'