
name: M-UnitTest_PSD_Test

on:
  schedule:
    - cron: '0 1 * * *'

  workflow_dispatch:
    inputs:
       logLevel:
          description: 'Log level'     
          required: true
          default: 'warning'
       tags:
          description: 'Test scenario tags'

jobs:
  check_date:
    runs-on: PSD
    name: Check latest commit
    outputs:
      should_run: ${{ steps.should_run.outputs.should_run }}
    steps:
    - run: |
        sudo chown -R $USER:$USER $GITHUB_WORKSPACE
    - uses: actions/checkout@v2
    - id: should_run
      name: check latest commit is less than a day
      if: ${{ github.event_name == 'schedule' }}
      working-directory: ${{github.workspace}}
      run: 
        date=`date -d "-24 hours" "+%s"`; result=`git rev-list -1 --after=$date main`
        test -z $result && echo "::set-output name=should_run::false"

  Unit_Test:
    needs: check_date
    if: ${{ needs.check_date.outputs.should_run != 'false' }}
    runs-on: PSD
    steps:
    - run: |
        echo "execute Unit_Test in M-UnitTest_PSD_Test"
